### ISSUE TITLE
Limit or Remove Table Pagination Feature

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#21]
The majority of the time we would rather do a bit of extra scrolling than deal with a pagination feature

### Table Pagination is `detrimental` in these context:
(i.e. we should see **ALL table rows** whenever a table is presented)
- Open hourlogs
- New time entries
- Current hourlog (all tables, especially `submitted` table)
- Closed hourlog (all tables)
- Companies
- Users

### Table pagination is `desirable` in this context:
- System-wide view of closed hour logs

### Table pagination is `neutral` in these context:
Eventually these will add up, but right now even the most heavily logged companies (DD9) probably have fewer than 100 hourlogs
- Company hourlogs
- Contractor hour logs (future feature)

**Comment by simmeringc** [comment]
Removed all pagination from tables, except for the system-wide view of closed hour logs. 

Since there's no default table size in tables with no pagination, it can seem like there's some visually distracting pop-in effects while the data asynchronously hydrates from the server to the client tables.

It's possible to fix this with a process called Server-side rendering, where the server's first response to the client is a built and hydrated GUI, and subsequent responses only rehydrate the GUI's state (data) instead of fetching all of the HTML to rebuild the GUI with a new state, like in non-react applications. SSR doesn't necessarily increase performance and is really just a strategy for improving the UI on page load, but its an advanced React topic that I'm looking into and will probably implement here to fix pop-in.

If you navigate around the site you'll notice that the tables on the client will retain their state and not have any pop-in side effects when you navigate away/back to a page. Pop-in only occurs on a fresh session where the state was null to begin with, so there's nothing to show. When a user navigates to and from pages or triggers ajax calls, the initial state will be stale instead of null, showing old data with no pop-in while an ajax call rehydrates the client with new data.
