### ISSUE TITLE
Admin & Staff should not have contractor hour logs

### ISSUE THREAD

**Issue by todditron** [DD9/dd9app#40]
I am not sure this hurts anything to have these hour logs here, but does potentially expose a logic or code flaw.

![image](https://user-images.githubusercontent.com/1143370/48045276-e32de500-e14c-11e8-81c5-50c8950bcc93.png)

**Comment by todditron** [comment]
That said, I can see how it might be a little useful to see all the non-adjudicated time entries for a staff or admin in one place. I just don't ever really see a need to close an hour log for anyone but a contractor

**Comment by simmeringc** [comment]
The user roles in this app function as a hierarchy from a design standpoint. If you're an Admin, you are also a staff member and a contractor, as in you work on client projects, so an admin will have a  contractorHourLog since he is logging timeEntries against clients.

We should come back to this after you use the system in production for a little bit.
